name: .NET Core

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: dotnet clean
      run: |  
          cd src
          dotnet clean
    - name: dotnet build
      run: |
          cd src
          dotnet build --configuration Release
    - name: dotnet pack
      run: |  
          cd src
          dotnet pack NBitpayClient/NBitpayClient.csproj --no-build --configuration Release -o out
    - name: publish to nuget
      run: | 
          dotnet nuget push ./src/out/*NBitpayClient.*.nupkg -k ${{ secrets.Nuget_tristan }} -s https://api.nuget.org/v3/index.json